version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: weekly
      time: '08:00'
    open-pull-requests-limit: 20
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
