name: Setup SAP RFC
description: Setup a SAP RFC environment by installing the SDK

inputs:
  os:
    description: 'Operating System (only supports linux)'
    default: 'linux'
    required: false
  patch-level:
    description: 'RFC SDK patch level (only supports 11)'
    default: '11'
    required: false
  sdk-version:
    description: 'RFC SDK version (only supports 750)'
    default: '750'
    required: false
  token:
    description: 'GitHub PAT'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: grupoboticario/actions-setup-sap-rfc
        path: setup-sap-rfc-sdk
        token: ${{ inputs.token }}
    - name: Run Action
      uses: ./setup-sap-rfc-sdk
      with:
        os: ${{ inputs.os }}
        patch-level: ${{ inputs.patch-level }}
        sdk-version: ${{ inputs.sdk-version }}
