name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '**/*.yaml'
      - '.github/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '**/*.yaml'
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Setup SAP RFC SDK
        uses: ./.github/actions/actions-setup-sap-rfc
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
        env:
          CI: true
  release:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Setup SAP RFC SDK
        uses: ./.github/actions/actions-setup-sap-rfc
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Install Dependencies
        run: npm ci
      - name: Semantic Release
        run: npm run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
