name: Publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org/
      - name: Setup SAP RFC SDK
        uses: ./.github/actions/actions-setup-sap-rfc
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
