name: 'Sonar'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '**/*.yaml'
      - '.github/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '**/*.yaml'
      - '.github/**'
  workflow_dispatch:

jobs:
  sonarAnalysis:
    name: Sonar Analysis
    runs-on: [ubuntu-latest]
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Setup SAP RFC SDK
        uses: ./.github/actions/actions-setup-sap-rfc
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test:cov
        env:
          CI: true
      - name: SonarCloud Scan
        uses: grupoboticario/actions-ci-sonarcloud@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
